### ISSUE TITLE
[맥-크롬-1920-강의페이지] 라이브 중인 강의가 아님에도 [라이브 강의 입장] 버튼 노출됨

### ISSUE THREAD

**Issue by bysoyeon** [100-hours-a-week/NemoOceanAcademy_fe#30]
##  버그 설명
강사가 라이브 중이지 않음에도 [라이브 강의 입장] 버튼이 보이고, 클릭 시 에러 화면이 노출 됨.

## 재현하는 방법
https://www.nemooceanacademy.com/dashboard/student/8

## 스크린샷 (옵션)
<img width="403" alt="image" src="https://github.com/user-attachments/assets/a63e5d06-9546-4338-95c7-5903f08ae98c">

## 데스크톱(다음 정보를 작성해 주세요):

- OS:  iOS
- Browser : chrome

**Comment by ehvzmf** [comment]
현재 더미 데이터에 무작위로 강의 중이라는 상태 설정을 해두었기 때문에 발생
-> 더미 데이터 삭제 예정.
