### ISSUE TITLE
[bug] 채팅이 한 줄로 나와요

### ISSUE THREAD

**Issue by dongmin132** [100-hours-a-week/NemoOceanAcademy_fe#33]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 채팅창 길어짐

## 재현하는 방법

동작을 재현하는 단계:

1. 채팅창에 글을 많이 입력

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 여러 줄로 나오길 바람

## 스크린샷 (옵션)

<img width="480" alt="image" src="https://github.com/user-attachments/assets/8ae62198-280a-492f-9e40-dbec412c31db">

## 데스크톱(다음 정보를 작성해 주세요):

- OS: [예) iOS]
- Browser [예) chrome, safari]
- Version [예) 22]

## 스마트폰(다음 정보를 입력하세요):

- Device: [예) iPhone6]
- OS: [예) iOS8.1]
- Browser [예) chrome, safari]
- Version [예) 22]

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by ehvzmf** [comment]
해결 완료했습니다
