### ISSUE TITLE
[Bug] 채팅 빈 내용이 보내져요

### ISSUE THREAD

**Issue by mepwj** [100-hours-a-week/NemoOceanAcademy_fe#34]
##  버그 설명

채팅 빈 내용이 보내져요
![스크린샷 2024-09-11 104850](https://github.com/user-attachments/assets/6943d018-4464-41d4-be47-f94482b04210)

- 버그 1
- 버그 2

## 재현하는 방법

동작을 재현하는 단계:

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 예상동작 1
- 예상동작 2

## 스크린샷 (옵션)

문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

## 데스크톱(다음 정보를 작성해 주세요):

- OS: [예) iOS]
- Browser [예) chrome, safari]
- Version [예) 22]

## 스마트폰(다음 정보를 입력하세요):

- Device: [예) iPhone6]
- OS: [예) iOS8.1]
- Browser [예) chrome, safari]
- Version [예) 22]

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by ehvzmf** [comment]
토니가 해결했습니다
토니 짱
