### ISSUE TITLE
[bug] 라이브 강의 채팅 시간 오류

### ISSUE THREAD

**Issue by bysoyeon** [100-hours-a-week/NemoOceanAcademy_fe#35]
##  버그 설명

- 채팅을 보내면 모든 채팅말풍선의 시간이 현재시간으로 변경 됨.
- 채팅 입력란에 아무 값을 입력하지 않고 엔터치면 얇은 채팅말풍선으로 전송됨.
- 2글자 보냈는데, 채팅말풍선의 디폴트 너비가 너무 길어서 우측에 공란이 있음.

## 스크린샷 (옵션)
<img width="403" alt="image" src="https://github.com/user-attachments/assets/2e536687-75c9-4b21-9ea6-5945ef3e522d">

문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

## 데스크톱(다음 정보를 작성해 주세요):

- OS: [예) iOS]
- Browser [예) chrome, safari]
- Version [예) 22]

**Comment by ehvzmf** [comment]
해결!
