### ISSUE TITLE
사용자 정보 수정 아이콘이 보이지 않습니다.

### ISSUE THREAD

**Issue by Ssun2zang** [100-hours-a-week/NemoOceanAcademy_fe#62]
아이콘이 흰색인지 보이지 않습니다.
<img width="393" alt="image" src="https://github.com/user-attachments/assets/7555b6d8-d47f-492c-8af2-e7c0be0c2928">

**Comment by ehvzmf** [comment]
즐리가 했다 
아이콘 > 텍스트로 변경
