### ISSUE TITLE
제공되지 않는 url에 접속시 에러 처리 로직 필요

### ISSUE THREAD

**Issue by Ssun2zang** [100-hours-a-week/NemoOceanAcademy_fe#65]
깨진 화면이 그대로 서빙되는 문제가 있습니다.
<img width="402" alt="image" src="https://github.com/user-attachments/assets/07be40d2-c767-4964-a0e2-204379de9a23">

**Comment by ehvzmf** [comment]
404 페이지 추가했습니다.
