### ISSUE TITLE
규격에 맞지 않는 강의 배너 이미지 처리 필요

### ISSUE THREAD

**Issue by Ssun2zang** [100-hours-a-week/NemoOceanAcademy_fe#66]
규격이 맞지 않는 이미지가 이상하게 보이는 문제가 있습니다.
<img width="404" alt="image" src="https://github.com/user-attachments/assets/dc1b3594-dd30-49c8-a8c9-a5871506794d">

**Comment by ehvzmf** [comment]
잘 보입니다요
