### ISSUE TITLE
mypage 사용자 수정하기 버튼 위치 문제

### ISSUE THREAD

**Issue by Ssun2zang** [100-hours-a-week/NemoOceanAcademy_fe#68]
이메일 길이가 길 경우에 사용자 수정 버튼이 컴포넌트를 벗어나는 문제가 있습니다. (사용자 이름은 괜찮습니다)
<img width="462" alt="image" src="https://github.com/user-attachments/assets/865419e7-fb23-41d3-b734-9ba67fc573d0">
<img width="400" alt="image" src="https://github.com/user-attachments/assets/106a8509-c6af-4c61-af21-668a750d06ff">

**Comment by ehvzmf** [comment]
왜지? 해결!
