### ISSUE TITLE
강의 정보 페이지 내용이 컴포넌트를 벗어나는 문제

### ISSUE THREAD

**Issue by Ssun2zang** [100-hours-a-week/NemoOceanAcademy_fe#70]
강의 목표, 강의 소개, 강사 소개, 사전 준비사항 내용이 길 경우 컴포넌트를 벗어나는 문제가 있습니다.
<img width="540" alt="image" src="https://github.com/user-attachments/assets/32f8b020-51d3-43f2-a936-3ba2314e6b8b">

**Comment by ehvzmf** [comment]
수정 완!
