### ISSUE TITLE
강의 대시보드 페이지 내용이 컴포넌트를 벗어나는 문제

### ISSUE THREAD

**Issue by Ssun2zang** [100-hours-a-week/NemoOceanAcademy_fe#71]
강의 목표, 강의 소개, 강사 소개, 사전 준비 사항 텍스트가 긴 경우 컴포넌트를 벗어나는 문제가 있습니다.
<img width="508" alt="image" src="https://github.com/user-attachments/assets/aa651024-5068-4962-ba23-0a9356c5c4e6">

**Comment by Ssun2zang** [comment]
'강의 공지'도 컴포넌트에 벗어나는 문제가 있습니다.
<img width="381" alt="image" src="https://github.com/user-attachments/assets/953854be-7f78-43e8-abae-67cf82808ab8">

**Comment by ehvzmf** [comment]
수정 완!
