### ISSUE TITLE
라이브 강의(수강생)에서 본인이 작성한 채팅이 '익명'으로 '좌측'에 표기됩니다

### ISSUE THREAD

**Issue by GoByeonghu** [100-hours-a-week/NemoOceanAcademy_fe#72]
##  버그 설명

라이브 강의(수강생)에서 본인이 작성한 채팅이 '익명'으로 '좌측'에 표기됩니다

## 스크린샷 

![image](https://github.com/user-attachments/assets/952faf48-aa80-4a88-ad2a-dbe1595919b9)
수강생 화면에서는 여전히 본인이 작성한 채팅이 '익명'으로 좌측에 표시됩니다

**Comment by ehvzmf** [comment]
스티븐 멋있는 척 하고 캡처한 거

**Comment by ehvzmf** [comment]
반영 완.
