### ISSUE TITLE
강사가 자신의 '강의 소개'에서 대시보드 가기를 누르면 '강의 대시보드 (student)'로 라우팅되는 문제

### ISSUE THREAD

**Issue by Ssun2zang** [100-hours-a-week/NemoOceanAcademy_fe#73]
강사가 자신의 강의를 `lecture/info/N`에서 '대시보드 가기' 버튼을 누를 경우, `dashboard/student/N`으로 라우팅되는 문제가 있습니다.
사용자 경험 상, 강사는 `dashboard/teacher/N`으로 이동하도록 변경해야할 것 같습니다.
<img width="512" alt="image" src="https://github.com/user-attachments/assets/28bececc-132d-4620-b34f-964d2b0b9d21">

**Comment by ehvzmf** [comment]
수정했습니다.
