### ISSUE TITLE
사용자 페이지에서 프로필 정보수정 버튼이 안보입니다.

### ISSUE THREAD

**Issue by GoByeonghu** [100-hours-a-week/NemoOceanAcademy_fe#77]
##  버그 설명

사용자 페이지에서 프로필 정보수정 버튼이 안보입니다.

## 스크린샷 

![image](https://github.com/user-attachments/assets/e260fdfc-efa8-479c-b4c4-da8923f3baf6)

**Comment by ehvzmf** [comment]
아이콘 없애고 '수정' 텍스트 버튼으로
