### ISSUE TITLE
전체 강의 조회 페이지에서 모든 강의가 로드되었는데도 무한히 스크롤 됩니다. 

### ISSUE THREAD

**Issue by GoByeonghu** [100-hours-a-week/NemoOceanAcademy_fe#78]
##  버그 설명

전체 강의 조회 페이지에서 모든 강의가 로드되었는데도 무한히 스크롤 됩니다. 
스크롤을 무한정 내릴수있으며 같은 강의리스트가 반복되어 불러와집니다.

## 스크린샷 (옵션)

![image](https://github.com/user-attachments/assets/39353585-9ced-4d95-a81a-a10891829d04)

**Comment by Ssun2zang** [comment]
즐리가 해결함
