### ISSUE TITLE
강의소개 페이지에서 베너이미지가 중복되어 표시됩니다.

### ISSUE THREAD

**Issue by GoByeonghu** [100-hours-a-week/NemoOceanAcademy_fe#79]
##  버그 설명

강의베너 이미지로 하나의 이미지를 업로드 하여도 강의 소개페이지에서는 여러개로 보입니다.

## 스크린샷 
![image](https://github.com/user-attachments/assets/c8cf5a9b-5800-42d3-b69e-c57578d10a64)

**Comment by ehvzmf** [comment]
괜찮은디?
