### ISSUE TITLE
classroom 에러 무한제공

### ISSUE THREAD

**Issue by ehvzmf** [100-hours-a-week/NemoOceanAcademy_fe#82]
콘솔에서 에러가 계속 뜹니다. 

<img width="618" alt="스크린샷 2024-09-26 오전 9 45 42" src="https://github.com/user-attachments/assets/24251bca-f1ac-4f02-a8a0-0e91c3876250">

**Comment by Ssun2zang** [comment]
이거 해결됐나요

**Comment by ehvzmf** [comment]
@Ssun2zang 지금은 안 떠요!
